AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Only'
Parameters:
  AMI:
    Description: AMI ID
    Type: String
    Default: '{{ environment.inputs.AMI }}'
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: '{{ environment.inputs.InstanceType }}'
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceType