schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "EC2EnvironmentInput"
  types:
    EC2EnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        AMI:
          description: "AMI used to launch the EC2 instances"
          type: string
          default: "ami-ceafcba8"
        InstanceType:
          description: "EC2 instance type"
          type: string
          default: "t2.small"