AWSTemplateFormatVersion: '2010-09-09'
Description: A stack for deploying containerized applications on EC2 clusters.
             This stack runs containers in a public or private VPC subnet. 

Mappings:
  # The VPC and subnet configuration is passed in via the environment spec.
  SubnetConfig:
    VPC:
      CIDR: '{{ environment.inputs.vpc_cidr}}'
    Public1:
      CIDR: '{{ environment.inputs.public_subnet_one_cidr}}'
    Public2:
      CIDR: '{{ environment.inputs.public_subnet_two_cidr}}'
    Private1:
      CIDR: '{{ environment.inputs.private_subnet_one_cidr}}'
    Private2:
      CIDR: '{{ environment.inputs.private_subnet_two_cidr}}'   

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Condition: InstanceCreationCondition
    Properties:
      ImageId: ami-ceafcba8
      InstanceType: t2.small